resources:
  repositories:
    - repository: templates
      type: github
      name: NSLS-II/profile-collection-ci
      ref: refs/heads/single-run-test-step
      endpoint: github

jobs:
  - template: collection-2019-3.0.1.yml@templates
    parameters:
      beamline_acronym: local
  - template: collection-2021-1.0.yml@templates
    parameters:
      beamline_acronym: local
